export const mozartSonataCaptions = [
  {
    id: 1,
    text: "Mozart's Piano Sonata in A minor, K.310",
    startTime: 0,
    endTime: 2,
    callEventType: 'schedule_appointment',
    time: '17:00 Today',
    type: 'call_event' as const,
  },
  {
    id: 2,
    text: 'Incoming Call from +44 20 7123 4567 (Jane Smith)',
    startTime: 2,
    endTime: 5,
    type: 'dial_event' as const,
  },
  {
    id: 3,
    text: 'The piece opens with dramatic intensity',
    startTime: 5,
    endTime: 10,
    type: 'ai' as const,
  },
  {
    id: 4,
    text: 'Rapid scales create a sense of urgency',
    startTime: 10,
    endTime: 15,
    type: 'ai' as const,
  },
  {
    id: 5,
    text: 'Left hand provides a turbulent bass line',
    startTime: 15,
    endTime: 20,
    type: 'ai' as const,
  },
  {
    id: 6,
    text: 'The melody becomes more agitated',
    startTime: 20,
    endTime: 25,
    type: 'ai' as const,
  },
  {
    id: 7,
    text: 'A moment of harmonic tension builds',
    startTime: 25,
    endTime: 30,
    callEventType: 'cancel_appointment',
    time: '17:30 Today',
    type: 'call_event' as const,
  },
  {
    id: 8,
    text: 'The emotional depth is overwhelming',
    startTime: 30,
    endTime: 35,
    type: 'user' as const,
  },
  {
    id: 9,
    text: 'Such passionate playing in this section',
    startTime: 35,
    endTime: 40,
    type: 'user' as const,
  },
  {
    id: 10,
    text: 'A series of dramatic chord progressions',
    startTime: 40,
    endTime: 45,
    type: 'ai' as const,
  },
  {
    id: 11,
    text: 'The dynamics shift suddenly to piano',
    startTime: 45,
    endTime: 50,
    type: 'ai' as const,
  },
  {
    id: 12,
    text: 'This contrast is so powerful',
    startTime: 50,
    endTime: 55,
    type: 'user' as const,
  },
  {
    id: 13,
    text: 'Building to a dramatic climax',
    startTime: 55,
    endTime: 60,
    type: 'ai' as const,
  },
  {
    id: 14,
    text: 'Mozart at his most emotionally intense',
    startTime: 60,
    endTime: 65,
    type: 'user' as const,
  },
  {
    id: 15,
    text: 'The tension continues to mount',
    startTime: 65,
    endTime: 70,
    type: 'ai' as const,
  },
  {
    id: 16,
    text: 'A masterpiece of dramatic expression',
    startTime: 70,
    endTime: 75,
    type: 'user' as const,
  },
];

export const mozartSonataCaptionWithAudio = {
  captions: mozartSonataCaptions,
  audioSrc:
    'https://upload.wikimedia.org/wikipedia/commons/9/98/Mozart_Piano_Sonata_Amin3.ogg',
};
