const mozartCaptions = [
  {
    id: 1,
    text: "Mozart's Piano Sonata in C Major, K.330 - Andante cantabile",
    startTime: 0,
    endTime: 2,
    callEventType: 'schedule_appointment',
    time: '16:00 Today',
    type: 'call_event' as const,
  },
  {
    id: 2,
    text: 'Incoming Call from +44 20 7123 4567 (Jane Smith)',
    startTime: 2,
    endTime: 5,
    type: 'dial_event' as const,
  },
  {
    id: 3,
    text: 'The movement begins with a serene melody',
    startTime: 5,
    endTime: 10,
    type: 'ai' as const,
  },
  {
    id: 4,
    text: 'Left hand provides gentle accompaniment',
    startTime: 10,
    endTime: 15,
    type: 'ai' as const,
  },
  {
    id: 5,
    text: 'A delicate trill ornaments the melody',
    startTime: 15,
    endTime: 20,
    type: 'ai' as const,
  },
  {
    id: 6,
    text: 'The theme develops with subtle variations',
    startTime: 20,
    endTime: 25,
    type: 'ai' as const,
  },
  {
    id: 7,
    text: 'Moving to a minor key section',
    startTime: 25,
    endTime: 30,
    callEventType: 'cancel_appointment',
    time: '16:30 Today',
    type: 'call_event' as const,
  },
  {
    id: 8,
    text: "Mozart's genius shines in these modulations",
    startTime: 30,
    endTime: 35,
    type: 'user' as const,
  },
  {
    id: 9,
    text: 'Such elegant phrasing in this performance',
    startTime: 35,
    endTime: 40,
    type: 'user' as const,
  },
  {
    id: 10,
    text: 'A series of ascending scales begins',
    startTime: 40,
    endTime: 45,
    type: 'ai' as const,
  },
  {
    id: 11,
    text: 'The harmony grows more chromatic',
    startTime: 45,
    endTime: 50,
    type: 'ai' as const,
  },
  {
    id: 12,
    text: 'The expressiveness is breathtaking',
    startTime: 50,
    endTime: 55,
    type: 'user' as const,
  },
  {
    id: 13,
    text: 'Returning to the main theme',
    startTime: 55,
    endTime: 60,
    type: 'ai' as const,
  },
  {
    id: 14,
    text: 'A perfect balance of emotion and form',
    startTime: 60,
    endTime: 65,
    type: 'user' as const,
  },
];

export const mozartCaptionWithAudio = {
  captions: mozartCaptions,
  audioSrc:
    'https://upload.wikimedia.org/wikipedia/commons/d/df/Wolfgang_Amadeus_Mozart_-_Klaviersonate_C-Dur_KV_330_%28300h%29_-_2-_Andante_cantabile_-_Schmidt_2000.ogg',
};
